linux-server:
  hosts:
    local:
      ansible_connection: local
    second_test_server:
      ansible_host: 192.168.1.107
      ansible_user: root
      ansible_password: zabuza22
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'