linux-server:
  hosts:
    local:
      ansible_connection: local
    second_test_server:
      ansible_host: 
      ansible_user: 
      ansible_password: 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'