---
# tasks file for testproject

- name: install the latest version of yum-utils
  yum:
    name: yum-utils
    state: present

- name: Set up the repository for docker
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install packages for docker
  yum:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: Ensure docker service is started
  systemd:
    state: started
    name: docker

- name: Clone git repo
  git:
    repo: https://github.com/Dishair/testproject.git
    dest: ~
    